### ISSUE TITLE
Bug No NetCDF variable...

### ISSUE THREAD

**Issue by Marie59** [fair-ease/Divand-Galaxy-ext#1]
Hi @ctroupin ! I am getting back on this notebook I already did some changes. However at the bloc 8 under the `## 1. Read your ODV file
`part I am having an error this one `No NetCDF variable found with attribute 'long_name' equal to 'Water body phosphate' in ../data/1_data_from_Eutrophication_Med_profiles_2022_unrestricted.netcdf`

I am pretty sure that's because I am not putting the right parameters to the NCODV function. Could you give me a hand ?

**Comment by ctroupin** [comment]
Hello Marie,
OK I guess the easier for me to find the issue is to re-run your code. 

As you've probably seen, `NCODV.load( )` has 3 arguments:
- `T` the type
- `fname` the file name and
- `long_name` the long name of the considered variable in the netCDF.

It seems in the netCDF none of the variables has an attribute `long_name` equal to 'Water body phosphate'. Can you put the output of the command `ncdump -h ../data/1_data_from_Eutrophication_Med_profiles_2022_unrestricted.netcdf` (in bash)?

**Comment by Marie59** [comment]
I did it locally (not easy to do in the galaxy jupyterlab). The output is very long here just the beginning of it 
`netcdf Eutrophication_Med_profiles_2022_unrestricted {
dimensions:
	N_STATIONS = 7990 ;
	N_SAMPLES = 5151 ;
	STRING15 = 15 ;
	STRING144 = 144 ;
	STRING33 = 33 ;
	STRING156 = 156 ;
	STRING4963 = 4963 ;
	STRING215 = 215 ;
	STRING705 = 705 ;
	STRING20 = 20 ;
	STRING8 = 8 ;
	STRING13 = 13 ;
	STRING3 = 3 ;
	STRING104 = 104 ;
	STRING18 = 18 ;
	STRING983 = 983 ;
	STRING28 = 28 ;
	STRING740 = 740 ;
	STRING21 = 21 ;
	STRING42 = 42 ;
	STRING27 = 27 ;
	STRING40 = 40 ;
	STRING36 = 36 ;
	STRING4 = 4 ;
	STRING49 = 49 ;
	STRING143 = 143 ;
	STRING60 = 60 ;
	STRING11 = 11 ;
	STRING339 = 339 ;
	STRING51 = 51 ;
	STRING257 = 257 ;
	STRING94 = 94 ;
	STRING52 = 52 ;
	STRING121 = 121 ;
	STRING6 = 6 ;
	STRING7 = 7 ;
	STRING263 = 263 ;
	STRING177 = 177 ;
variables:
	char metavar1(N_STATIONS, STRING28) ;
		metavar1:long_name = "Cruise" ;
		metavar1:units = "" ;
		metavar1:comment = "" ;
		metavar1:ancillary_variables = "metavar1_qc" ;
	byte metavar1_qc(N_STATIONS) ;
		metavar1_qc:long_name = "Quality flag of Cruise" ;
		metavar1_qc:standard_name = "status_flag" ;
		metavar1_qc:comment = "ODV - ODV generic quality codes" ;
		metavar1_qc:flag_values = 48b, 49b, 52b, 56b ;
		metavar1_qc:flag_meanings = "good_quality unknown_quality questionable_quality bad_quality" ;
		metavar1_qc:_FillValue = 49b ;
	char metavar2(N_STATIONS, STRING20) ;
		metavar2:long_name = "Station" ;
		metavar2:units = "" ;
		metavar2:comment = "" ;
		metavar2:ancillary_variables = "metavar2_qc" ;
	byte metavar2_qc(N_STATIONS) ;
		metavar2_qc:long_name = "Quality flag of Station" ;
		metavar2_qc:standard_name = "status_flag" ;
		metavar2_qc:comment = "ODV - ODV generic quality codes" ;
		metavar2_qc:flag_values = 48b, 49b, 52b, 56b ;
		metavar2_qc:flag_meanings = "good_quality unknown_quality questionable_quality bad_quality" ;
		metavar2_qc:_FillValue = 49b ;
	char metavar3(N_STATIONS) ;
		metavar3:long_name = "Type" ;
		metavar3:units = "" ;
		metavar3:comment = "" ;
		metavar3:ancillary_variables = "metavar3_qc" ;
	byte metavar3_qc(N_STATIONS) ;
		metavar3_qc:long_name = "Quality flag of Type" ;
		metavar3_qc:standard_name = "status_flag" ;
		metavar3_qc:comment = "ODV - ODV generic quality codes" ;
		metavar3_qc:flag_values = 48b, 49b, 52b, 56b ;
		metavar3_qc:flag_meanings = "good_quality unknown_quality questionable_quality bad_quality" ;
		metavar3_qc:_FillValue = 49b ;
	float longitude(N_STATIONS) ;
		longitude:long_name = "Longitude" ;
		longitude:standard_name = "longitude" ;
		longitude:units = "degrees_east" ;
		longitude:comment = "" ;
		longitude:ancillary_variables = "longitude_qc" ;
		longitude:C_format = "%.3f" ;
		longitude:FORTRAN_format = "F12.3" ;
		longitude:_FillValue = -1.e+10f ;
	byte longitude_qc(N_STATIONS) ;
		longitude_qc:long_name = "Quality flag of Longitude" ;
		longitude_qc:standard_name = "status_flag" ;
		longitude_qc:comment = "ODV - ODV generic quality codes" ;
		longitude_qc:flag_values = 48b, 49b, 52b, 56b ;
		longitude_qc:flag_meanings = "good_quality unknown_quality questionable_quality bad_quality" ;
		longitude_qc:_FillValue = 49b ;
	float latitude(N_STATIONS) ;
		latitude:long_name = "Latitude" ;
		latitude:standard_name = "latitude" ;
		latitude:units = "degrees_north" ;
		latitude:comment = "" ;
		latitude:ancillary_variables = "latitude_qc" ;
		latitude:C_format = "%.3f" ;
		latitude:FORTRAN_format = "F12.3" ;
		latitude:_FillValue = -1.e+10f ;
	byte latitude_qc(N_STATIONS) ;
		latitude_qc:long_name = "Quality flag of Latitude" ;
		latitude_qc:standard_name = "status_flag" ;
		latitude_qc:comment = "ODV - ODV generic quality codes" ;
		latitude_qc:flag_values = 48b, 49b, 52b, 56b ;
		latitude_qc:flag_meanings = "good_quality unknown_quality questionable_quality bad_quality" ;
		latitude_qc:_FillValue = 49b ;
	char metavar4(N_STATIONS, STRING42) ;
		metavar4:long_name = "LOCAL_CDI_ID" ;
		metavar4:units = "" ;
		metavar4:comment = "" ;
		metavar4:ancillary_variables = "metavar4_qc" ;
	byte metavar4_qc(N_STATIONS) ;
		metavar4_qc:long_name = "Quality flag of LOCAL_CDI_ID" ;
		metavar4_qc:standard_name = "status_flag" ;
		metavar4_qc:comment = "SEADATANET - SeaDataNet quality codes" ;
		metavar4_qc:flag_values = 48b, 49b, 50b, 51b, 52b, 53b, 54b, 55b, 56b, 57b, 65b, 66b, 81b ;
		metavar4_qc:flag_meanings = "no_quality_control good_value probably_good_value probably_bad_value bad_value changed_value value_below_detection value_in_excess interpolated_value missing_value value_phenomenon_uncertain nominal_value value_below_limit_of_quantification" ;
		metavar4_qc:_FillValue = 57b ;
	int metavar5(N_STATIONS) ;
		metavar5:long_name = "EDMO_code" ;
		metavar5:units = "" ;
		metavar5:comment = "" ;
		metavar5:ancillary_variables = "metavar5_qc" ;
		metavar5:C_format = "%.0f" ;
		metavar5:FORTRAN_format = "F12.0" ;
		metavar5:_FillValue = -2147483646 ;
	byte metavar5_qc(N_STATIONS) ;
		metavar5_qc:long_name = "Quality flag of EDMO_code" ;
		metavar5_qc:standard_name = "status_flag" ;
		metavar5_qc:comment = "SEADATANET - SeaDataNet quality codes" ;
		metavar5_qc:flag_values = 48b, 49b, 50b, 51b, 52b, 53b, 54b, 55b, 56b, 57b, 65b, 66b, 81b ;
		metavar5_qc:flag_meanings = "no_quality_control good_value probably_good_value probably_bad_value bad_value changed_value value_below_detection value_in_excess interpolated_value missing_value value_phenomenon_uncertain nominal_value value_below_limit_of_quantification" ;
		metavar5_qc:_FillValue = 57b ;
`

**Comment by Marie59** [comment]
If needed I can share my galaxy history with you and quickly explain some details on how I proceed and you can try it too.

**Comment by ctroupin** [comment]
ok I see. The idea was to check if there is (at least) one variable in the netCDF that has an attribute "long_name" equal to 'Water body phosphate'. If not then NCODV.read cannot read anything.

**Comment by Marie59** [comment]
So for instance I should write  Eutrophication_Med_profiles_2022_unrestricted  this instead of 'Water body phosphate'. ?

**Comment by Marie59** [comment]
Ah no okay I understand ! But how can I know which variable I should choose ? Is it interesting to take this one "Quality flag of Water body nitrate"

**Comment by ctroupin** [comment]
During the export with ODV you should have been able to select those variables you want in the netCDF. For instance temperature, salinity, etc. In the netCDF the variable names can be var01, var02, etc so that's why we use their `long_name`.

So now it depends which variables are in the netCDF.

**Comment by ctroupin** [comment]
During the export with ODV you should have been able to select those variables you want in the netCDF. For instance temperature, salinity, etc. In the netCDF the variable names can be var01, var02, etc so that's why we use their `long_name`.

So now it depends which variables are in the netCDF.

**Comment by Marie59** [comment]
Okay so I used the "Water body nitrate" variable for now and it's working !! I am moving forward and I see if I can fix the issues myself ! Thanks

**Comment by Marie59** [comment]
I think I have something running quite nicely ;) Might need some improvement but it's working
